// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMYKzWzeelO7Apixlm1IKBMA9nHM2lpMs',
    appId: '1:809979209002:android:1ea91b8874b305bbd8ea53',
    messagingSenderId: '809979209002',
    projectId: 'study-app-b5b77',
    databaseURL: 'https://study-app-b5b77-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'study-app-b5b77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2gLOMjA0tkZzhkoYrQtB0rKcH3j17wJs',
    appId: '1:809979209002:ios:bb76c266c1325204d8ea53',
    messagingSenderId: '809979209002',
    projectId: 'study-app-b5b77',
    databaseURL: 'https://study-app-b5b77-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'study-app-b5b77.appspot.com',
    iosClientId: '809979209002-s33rrha2hlg0j8ee2ofsl2kh29mq0sjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyAppFirebase',
  );
}
